# Generated by Django 4.2.14 on 2024-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField(help_text='in minutes')),
                ('cooking_time', models.PositiveBigIntegerField()),
                ('difficulty', models.CharField(max_length=20)),
            ],
        ),
    ]
